tiny updates

diff --git a/.github/workflows/k3.yml b/.github/workflows/k3.yml
--- a/.github/workflows/k3.yml
+++ b/.github/workflows/k3.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches:
       - master
-  # pull_request:
   workflow_call:
     inputs:
       kernel_version:
@@ -120,5 +119,11 @@ jobs:
           echo "Booting QEMU with Linux $KERNEL_VERSION..."
           qemu-system-x86_64 -kernel linux-${{ env.KERNEL_VERSION }}/arch/x86/boot/bzImage \
                              -initrd initramfs.cpio.gz \
-                             -append "console=ttyS0 rootfstype=ramfs" -nographic -no-reboot -m 1024
+                             -append "console=ttyS0 rootfstype=ramfs" -nographic -no-reboot -m 1024 2>&1 | tee qemu-output.log
+                      
+          if grep -q "panicked at " qemu-output.log; then
+            echo "error: unexpected error in QEMU run"
+            exit 1
+          fi
+
           echo "QEMU run completed."
